POST http://localhost:5000/invoices HTTP/1.1
content-type: application/json

{
  "InvoiceNumber": "123456",
  "CompanyName": "Acme Ltd.",
  "CompanyAddress": {
    "Line1": "Mansfield House",
    "TownCity": "London",
    "Zip": "WC12 4HP"
  },
  "Currency": "GBP",
  "Title": "Invoice from Acme",
  "Recipient": {
    "Name": "John Doe",
    "Email": "johndoh@gmail.com"
  },
  "Items": [
    {
      "Title": "Website design",
      "Amount": 300.00
    },
    {
      "Title": "Hosting (3 months)",
      "Amount": 75.00
    },
    {
      "Title": "Domain name (1 year)",
      "Amount": 10.00
    }
  ],
  "LogoUrl": "https://upload.wikimedia.org/wikipedia/commons/8/80/Logo_acme.svg"
}
