POST http://localhost:5000/invoices HTTP/1.1
content-type: application/json

{
  "invoice_number": "123456",
  "company_name": "Acme Ltd.",
  "company_address": {
    "line1": "Mansfield House",
    "town_city": "London",
    "zip": "WC12 4HP"
  },
  "currency": "GBP",
  "title": "Invoice from Acme",
  "recipient": {
    "name": "John Doe",
    "email": "johndoh@gmail.com"
  },
  "items": [
    {
      "title": "Website design",
      "amount": 300.00
    },
    {
      "title": "Hosting (3 months)",
      "amount": 75.00
    },
    {
      "title": "Domain name (1 year)",
      "amount": 10.00
    }
  ],
  "logo_url": "https://upload.wikimedia.org/wikipedia/commons/8/80/Logo_acme.svg"
}
